### ISSUE TITLE
Story does not have reference to user ID that created it

### ISSUE THREAD

**Issue by jamestyack** [civicmakers/client#105]
... and the 'created by' section on the story page is not the user...it's the project logo/name!
- Firebase needs a pointer in the project object to the user id that was logged in when the project was added
- UI needs to be updated to pull in the field

**Comment by ybentz** [comment]
@jamestyack, @grodeska I just merged a fix for this one, can one of you run a quick test and close the issue if fixed?
All current tools/stories won't have created by headline at all unless we add it manually but from now on when a story/tool is added it will show up automatically.

Fixed by:
https://github.com/civicmakers/client/pull/113
https://github.com/civicmakers/client/pull/114

**Comment by grodeska** [comment]
@ybentz won't be able to test this for a bit but will do it as as soon as I can.
