### ISSUE TITLE
Direct URLs/routes to stories, tools etc. result in 404 errors

### ISSUE THREAD

**Issue by jamestyack** [civicmakers/client#106]
Go to the story or tools list and click the refresh button (or copy paste the entire URL). Get a 'page not found' / 404 error.

**Comment by ybentz** [comment]
This happens because we're using html5mode which removes the # from the app's urls.
Since angular is a single page application framework everything is basically one page but the routes change the inner content - the router reads what's after the # and loads the wanted content dynamically.
if you try going to https://civicmakers.firebaseapp.com#/projects then it'll load but the # will be removed.

Usually the solution is server rewrites, firebase offers a solution for it since we don't really have a server.
Another option will be to drop the html5mode and have a # sign in the url.

**Comment by ybentz** [comment]
Fixed on https://github.com/civicmakers/client/pull/107

**Comment by jamestyack** [comment]
Cool, thanks for explanation. @eternal77 and I were chatting client side routing yesterday and how usually there is hash so this is pretty relevant. Did you fix by dropping html5 mode?

**Comment by jamestyack** [comment]
Sorry, @eternal44 not 77
